server:
  port: 8090

spring:
  application:
    name: buy-it

  data:
    mongodb:
      uri: mongodb+srv://ingo:qFwuU6lJHI9kkHbl@buyit.9ga1j.mongodb.net/product_db?retryWrites=true&w=majority&appName=BuyIt
      database: product_db
